apiVersion: v1
kind: Service
metadata:
  name: public-api-docs
  namespace: stashfi
  labels:
    app: public-api-docs
spec:
  type: ClusterIP
  selector:
    app: public-api-docs
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
